# Generated by Django 5.2.3 on 2025-06-13 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selfie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='selfies/')),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
